id: AC67944D5
title: fA389
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 19:44:15.468972
  last_modified_at: 2022-05-27 19:44:15.468975
