id: AC67944D5
title: fD1A9
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 19:44:15.488335
  last_modified_at: 2022-05-27 19:44:15.488338
