id: AC67944D5
title: f4FC6
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 19:44:15.423254
  last_modified_at: 2022-05-27 19:44:15.423257
